-- ============================================================
-- EduRoot API v1 — database migrations
-- Run once on your MySQL database before deploying Api_v1.php
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. Refresh token store
--    Raw tokens are never stored — only SHA-256 hashes.
--    Rotation: on /auth/refresh the old row is revoked and
--    a new row is inserted. Expired rows are cleaned by cron.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `api_refresh_tokens` (
    `id`          INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `user_id`     INT UNSIGNED    NOT NULL COMMENT 'users.id',
    `token_hash`  VARCHAR(64)     NOT NULL COMMENT 'SHA-256 of the raw token',
    `expires_at`  DATETIME        NOT NULL,
    `revoked`     TINYINT(1)      NOT NULL DEFAULT 0,
    `created_at`  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_token_hash` (`token_hash`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_expires` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='JWT refresh tokens for /api/v1/auth/refresh';


-- ─────────────────────────────────────────────────────────────
-- 2. AI remark cache
--    One row per student × exam group × language.
--    Generated by POST /api/v1/ai/report-card-remark
--    and surfaced in GET /api/v1/exams/{id}/result as ai_remark.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `ai_remarks` (
    `id`              INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `exam_group_id`   INT UNSIGNED    NOT NULL COMMENT 'exam_groups.id',
    `student_id`      INT UNSIGNED    NOT NULL COMMENT 'students.id',
    `lang`            VARCHAR(5)      NOT NULL DEFAULT 'en',
    `remark`          TEXT            NOT NULL,
    `generated_at`    DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_exam_student_lang` (`exam_group_id`, `student_id`, `lang`),
    KEY `idx_student` (`student_id`),
    KEY `idx_exam_group` (`exam_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='AI-generated report card remarks (cached from Claude API)';


-- ─────────────────────────────────────────────────────────────
-- 3. Fee risk cache
--    Weekly snapshot of students at risk of missing payments.
--    Populated by a cron job — GET /api/v1/ai/fee-risk reads this.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `fee_risk_cache` (
    `id`              INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `student_id`      INT UNSIGNED    NOT NULL COMMENT 'students.id',
    `session_id`      INT UNSIGNED    NOT NULL COMMENT 'sessions.id',
    `risk_score`      DECIMAL(4,3)    NOT NULL COMMENT '0.000 – 1.000',
    `risk_factors`    JSON            NULL,
    `suggested_action` TEXT           NULL,
    `computed_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_student_session` (`student_id`, `session_id`),
    KEY `idx_risk_score` (`risk_score`),
    KEY `idx_session` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Weekly fee payment risk scores — see docs/api/api-spec-v1.md';


-- ─────────────────────────────────────────────────────────────
-- 4. API rate limit tracker
--    One row per IP × endpoint_group × window.
--    Window = 1 minute. Cleaned daily by cron.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS `api_rate_limits` (
    `id`             INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    `ip`             VARCHAR(45)     NOT NULL COMMENT 'Supports IPv6',
    `endpoint_group` VARCHAR(32)     NOT NULL COMMENT 'auth | ai | default',
    `hits`           SMALLINT        NOT NULL DEFAULT 1,
    `window_start`   DATETIME        NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_ip_group_window` (`ip`, `endpoint_group`, `window_start`),
    KEY `idx_window` (`window_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='API rate limiting — 1-minute windows';
